# Generated by Django 4.1.5 on 2024-01-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_alter_userdetails_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profile_image',
            field=models.BinaryField(blank=True),
        ),
    ]
