# Generated by Django 4.1.5 on 2024-01-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_alter_userdetails_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_image',
            field=models.TextField(),
        ),
    ]
